@echo off
REM Build script for bg2ee-vanilla-langpack-ja_JP release package (Windows)

setlocal EnableDelayedExpansion

REM Configuration
set MOD_NAME=bg2ee-vanilla-langpack-ja_JP
set VERSION=v2.6.6.0
set WEIDU_VERSION=249.00
set WEIDU_URL=https://github.com/WeiDUorg/weidu/releases/download/v%WEIDU_VERSION%/WeiDU-Windows-249-amd64.zip

REM Directory setup
set RELEASE_DIR=release
set PACKAGE_DIR=%RELEASE_DIR%\%MOD_NAME%

echo === Building release package for %MOD_NAME% ===
echo Target version: %VERSION%
echo.

REM Clean previous builds
if exist "%RELEASE_DIR%" (
    echo Cleaning previous release directory...
    rmdir /s /q "%RELEASE_DIR%"
)

REM Create release directory structure
echo Creating release directory structure...
mkdir "%PACKAGE_DIR%"

REM Copy mod files
echo Copying mod files...
xcopy /E /I /Q "%VERSION%" "%PACKAGE_DIR%\%VERSION%"
copy README.md "%PACKAGE_DIR%\"

REM Copy installation scripts
if exist "install.sh" copy "install.sh" "%PACKAGE_DIR%\"
if exist "install.bat" copy "install.bat" "%PACKAGE_DIR%\"

REM Copy build-tlk scripts (optional, for advanced users)
if exist "build-tlk.sh" copy "build-tlk.sh" "%PACKAGE_DIR%\"
if exist "build-tlk.bat" copy "build-tlk.bat" "%PACKAGE_DIR%\"

REM Check if TP2 file exists
if not exist "setup-%MOD_NAME%.tp2" (
    echo WARNING: setup-%MOD_NAME%.tp2 not found. You need to create it before release.
) else (
    copy "setup-%MOD_NAME%.tp2" "%PACKAGE_DIR%\"
)

REM Remove TLK files from the package (they will be generated by users)
echo Removing TLK files (to be generated by users)...
del /S /Q "%PACKAGE_DIR%\*.tlk" 2>nul

REM Download WeiDU
echo Downloading WeiDU %WEIDU_VERSION%...
cd "%RELEASE_DIR%"
curl -L -o weidu.zip "%WEIDU_URL%"

REM Extract WeiDU using tar (built into Windows 10+)
echo Extracting WeiDU...
tar -xf weidu.zip 2>nul
if errorlevel 1 (
    REM Fallback to PowerShell if tar fails
    powershell -NoProfile -ExecutionPolicy Bypass -Command "& {Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory('weidu.zip', '.')}"
)

REM Rename WeiDU executable
echo Renaming WeiDU executable...
if exist "weidu.exe" (
    move weidu.exe "setup-%MOD_NAME%.exe"
) else if exist "WeiDU.exe" (
    move WeiDU.exe "setup-%MOD_NAME%.exe"
) else if exist "WeiDU-Windows\weidu.exe" (
    move "WeiDU-Windows\weidu.exe" "setup-%MOD_NAME%.exe"
    rmdir /s /q "WeiDU-Windows"
) else (
    echo WARNING: Could not find weidu.exe in the archive
)

REM Clean up zip file
del weidu.zip

REM Create final archive using tar (built into Windows 10+)
echo Creating release archive...
set ARCHIVE_NAME=%MOD_NAME%-%VERSION%.zip
tar -a -cf "%ARCHIVE_NAME%" "setup-%MOD_NAME%.exe" "%MOD_NAME%" 2>nul
if errorlevel 1 (
    REM Fallback to PowerShell if tar fails
    powershell -NoProfile -ExecutionPolicy Bypass -Command "& {Add-Type -AssemblyName System.IO.Compression.FileSystem; $zip = [System.IO.Compression.ZipFile]::Open('%ARCHIVE_NAME%', 'Create'); $zip.CreateEntryFromFile('setup-%MOD_NAME%.exe', 'setup-%MOD_NAME%.exe'); Get-ChildItem -Path '%MOD_NAME%' -Recurse | ForEach-Object { if (-not $_.PSIsContainer) { $relativePath = $_.FullName.Substring((Get-Location).Path.Length + 1); [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, $relativePath) } }; $zip.Dispose()}"
)

echo.
echo === Release package created successfully! ===
echo Location: %RELEASE_DIR%\%ARCHIVE_NAME%
echo.

cd ..
echo Done!
pause
